/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author hsavaryjackson
 */
public class frmReduce extends javax.swing.JFrame {

    /**
     * Creates new form inpForm
     */
    public frmReduce(Point location) {
	initComponents();
	try {
	    Image logo= ImageIO.read(new File("src/images/add_image.png")).getScaledInstance(btnNew.getWidth(), btnNew.getHeight(), Image.SCALE_SMOOTH);
	    btnNew.setIcon(new ImageIcon(logo));
	} catch (MalformedURLException ex) {
	    Logger.getLogger(frmHub.class.getName()).log(Level.SEVERE, null, ex);
	} catch (IOException ex) {
	    Logger.getLogger(frmHub.class.getName()).log(Level.SEVERE, null, ex);
	}
	setLocation(location);
	
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnHub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        spinAmount = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRecord = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your reductions");
        setPreferredSize(new java.awt.Dimension(421, 750));
        getContentPane().setLayout(null);

        btnHub.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        btnHub.setText("back");
        btnHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHubActionPerformed(evt);
            }
        });
        getContentPane().add(btnHub);
        btnHub.setBounds(22, 17, 72, 24);

        jLabel1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel1.setText("Used ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 93, 62, 38);

        cmbItems.setFont(new java.awt.Font("Futura", 0, 22)); // NOI18N
        cmbItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbItems);
        cmbItems.setBounds(114, 145, 173, 29);

        spinAmount.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        spinAmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(spinAmount);
        spinAmount.setBounds(184, 93, 85, 31);

        jLabel2.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel2.setText("Instead of ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(132, 192, 134, 32);

        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(134, 506, 117, 114);

        jLabel3.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel3.setText("(AMOUNT) (ITEM)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(91, 242, 222, 32);

        jLabel4.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel4.setText("You saved () Kg!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(104, 401, 193, 32);

        btnRecord.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        btnRecord.setText("RECORD");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecord);
        btnRecord.setBounds(110, 317, 187, 43);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubActionPerformed
        // TODO add your handling code here:
	frmHub hub = new frmHub(getLocation());
	
	dispose();
    }//GEN-LAST:event_btnHubActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
	new dlgSwap( new Point(  getLocation().x,  getLocation().y + (getWidth()/2) ) ).setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHub;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRecord;
    private javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinAmount;
    // End of variables declaration//GEN-END:variables
    
}
