package forms;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import util.ReuseSwap;

public class frmReduce extends AppForm {

    /**
     * Creates new form inpForm
     */
    public frmReduce(Point location, JsonObject _data) {
	super(_data);
	initComponents();
	try {
	    Image logo= ImageIO.read(new File("src/images/add_image.png")).getScaledInstance(btnNew.getWidth()-10, btnNew.getHeight()-10, Image.SCALE_SMOOTH);
	    btnNew.setIcon(new ImageIcon(logo));
	} catch (MalformedURLException ex) {
	    Logger.getLogger(frmHub.class.getName()).log(Level.SEVERE, null, ex);
	} catch (IOException ex) {
	    Logger.getLogger(frmHub.class.getName()).log(Level.SEVERE, null, ex);
	}
	
	setLocation(location);
	
	dReuse = data.getAsJsonObject("REUSE").getAsJsonPrimitive("total").getAsDouble();
	
	JsonArray jsonArr = data.getAsJsonArray("SWAPS");
	for (JsonElement e : jsonArr){
	    swaps.add(new GsonBuilder().create().fromJson(e, ReuseSwap.class));
	    cmbItems.addItem(e.getAsJsonObject().getAsJsonPrimitive("nameRecyclable").getAsString());
	}
	
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnHub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        spinAmount = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        lblNonRecycle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRecord = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your reductions");
        setPreferredSize(new java.awt.Dimension(421, 750));
        getContentPane().setLayout(null);

        btnHub.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        btnHub.setText("back");
        btnHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHubActionPerformed(evt);
            }
        });
        getContentPane().add(btnHub);
        btnHub.setBounds(22, 17, 72, 24);

        jLabel1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel1.setText("Used ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 93, 62, 38);

        cmbItems.setFont(new java.awt.Font("Futura", 0, 22)); // NOI18N
        cmbItems.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemsItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbItems);
        cmbItems.setBounds(114, 145, 173, 29);

        spinAmount.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        spinAmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spinAmountPropertyChange(evt);
            }
        });
        getContentPane().add(spinAmount);
        spinAmount.setBounds(184, 93, 85, 31);

        jLabel2.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel2.setText("Instead of ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(132, 192, 134, 32);

        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(134, 506, 117, 114);

        lblNonRecycle.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        lblNonRecycle.setText("(AMOUNT) (ITEM)");
        getContentPane().add(lblNonRecycle);
        lblNonRecycle.setBounds(91, 242, 222, 32);

        jLabel4.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel4.setText("You saved () Kg!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(104, 401, 193, 32);

        btnRecord.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        btnRecord.setText("RECORD");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecord);
        btnRecord.setBounds(110, 317, 187, 43);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubActionPerformed
        // TODO add your handling code here:
	frmHub hub = new frmHub(getLocation(),data);
	
	dispose();
    }//GEN-LAST:event_btnHubActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
	new dlgSwap( new Point(  getLocation().x,  getLocation().y + (getWidth()/2) ), this ).setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        // TODO add your handling code here:
	int index;
    }//GEN-LAST:event_btnRecordActionPerformed

    private void cmbItemsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemsItemStateChanged
        // TODO add your handling code here:
	if (evt.getStateChange() == ItemEvent.SELECTED){ 
	    int index = cmbItems.getSelectedIndex();
	    updateLabel(index);
	}
    }//GEN-LAST:event_cmbItemsItemStateChanged

    private void spinAmountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spinAmountPropertyChange
        // TODO add your handling code here:
	
    }//GEN-LAST:event_spinAmountPropertyChange

    private void updateLabel(int index){
	ReuseSwap currSwap = swaps.get(index);
	amount = (Integer)spinAmount.getValue();
	double dAmount = amount * currSwap.dRatio;
	lblNonRecycle.setText(String.valueOf(dAmount) + " " + currSwap.nameNonRecyclable);
    }
    
    public double dReuse;
    int amount ;
    
    ArrayList<ReuseSwap> swaps = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHub;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRecord;
    private javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNonRecycle;
    private javax.swing.JSpinner spinAmount;
    // End of variables declaration//GEN-END:variables
    
}
