package forms;

import com.google.gson.JsonObject;
import java.awt.Point;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author hsavaryjackson
 */
public class frmWaste extends AppForm {

    /**
     * Creates new form inpForm
     */
    public frmWaste(Point location, JsonObject _data) {
	super(_data);
	initComponents();
	
	JsonObject waste = data.getAsJsonObject("WASTE");
	JsonObject month = waste.getAsJsonObject("2022 APRIL") ;
	
	dRecyclable = month.getAsJsonPrimitive("total_recyclable").getAsDouble();
	dNonRecyclable = month.getAsJsonPrimitive("total_non_recyclable").getAsDouble();
	dTotalRecyclable =  waste.getAsJsonPrimitive("total_recyclable").getAsDouble();
	dTotalNonRecyclable = waste.getAsJsonPrimitive("total_non_recyclable").getAsDouble();
	
	setLocation(location);
	
	JPanel pnlRecyclable = new JPanel();
	JPanel pnlNonRecyclable = new JPanel();
	
	pnlRecyclable.setLayout(new BoxLayout(pnlRecyclable,BoxLayout.Y_AXIS));
	pnlNonRecyclable.setLayout(new BoxLayout(pnlNonRecyclable,BoxLayout.Y_AXIS));
	
	JScrollPane scrlRecyclable = new JScrollPane(pnlRecyclable,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	JScrollPane scrlNonRecyclable = new JScrollPane(pnlNonRecyclable,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	
	pnlNonRecyclable.add(new pnlWasteBulk(this,pnlWaste.typeOfWaste.NON_RECYCLABLE));
	pnlNonRecyclable.add(new pnlWaste("sandwich boxes","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.NON_RECYCLABLE));
	pnlNonRecyclable.add(new pnlWaste("chip bags","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.NON_RECYCLABLE));
	pnlNonRecyclable.add(new pnlWaste("salad tubs","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.NON_RECYCLABLE));
	pnlNonRecyclable.add(new pnlWaste("raisin bags","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.NON_RECYCLABLE));
	pnlNonRecyclable.add(new pnlWaste("sippy bags","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.NON_RECYCLABLE));
	
	pnlRecyclable.add(new pnlWasteBulk(this,pnlWaste.typeOfWaste.RECYCLABLE));
	pnlRecyclable.add(new pnlWaste("yoghurt tubs","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.RECYCLABLE));
	pnlRecyclable.add(new pnlWaste("plastic water bottles","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.RECYCLABLE));
	pnlRecyclable.add(new pnlWaste("bread bags","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.RECYCLABLE));
	pnlRecyclable.add(new pnlWaste("bottle tops","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.RECYCLABLE));
	pnlRecyclable.add(new pnlWaste("milk sachets","src/images/re_cubed_logo_bg.png",0.5,this,pnlWaste.typeOfWaste.RECYCLABLE));
	
	tabWaste.addTab("RECYCLABLE", scrlRecyclable);
	tabWaste.addTab("NON-RECYCLABLE", scrlNonRecyclable);
	
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHub = new javax.swing.JButton();
        tabWaste = new javax.swing.JTabbedPane();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your waste");
        setPreferredSize(new java.awt.Dimension(421, 750));
        getContentPane().setLayout(null);

        btnHub.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        btnHub.setText("back");
        btnHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHubActionPerformed(evt);
            }
        });
        getContentPane().add(btnHub);
        btnHub.setBounds(21, 17, 72, 24);
        getContentPane().add(tabWaste);
        tabWaste.setBounds(21, 53, 383, 693);

        btnInfo.setFont(new java.awt.Font("Futura", 0, 22)); // NOI18N
        btnInfo.setText("?");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo);
        btnInfo.setBounds(350, 16, 50, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubActionPerformed
	save();
	frmHub hub =new frmHub(getLocation(),data);
	dispose();
    }//GEN-LAST:event_btnHubActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
	new frmInfo(getLocation(),data);
	
	dispose();
    }//GEN-LAST:event_btnInfoActionPerformed

    public double dRecyclable;
    public double dNonRecyclable;
    public double dTotalRecyclable;
    public double dTotalNonRecyclable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHub;
    private javax.swing.JButton btnInfo;
    private javax.swing.JTabbedPane tabWaste;
    // End of variables declaration//GEN-END:variables

    @Override
    void save(){
	
	JsonObject waste = data.getAsJsonObject("WASTE");
	JsonObject month = waste.getAsJsonObject("2022 APRIL") ;
	
	month.addProperty("total_recyclable", dRecyclable);
	month.addProperty("total_non_recyclable", dNonRecyclable);
	waste.addProperty("total_recyclable",dTotalRecyclable);
	waste.addProperty("total_non_recyclable",dTotalNonRecyclable);
    }
   
}
