/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hsavaryjackson
 */
public class pnlWaste extends javax.swing.JPanel {

    public enum typeOfWaste {
	RECYCLABLE,NON_RECYCLABLE
    }
    /**
     * Creates new form pnlWaste
     */
    public pnlWaste(String name, String iconPath, double kilo, frmWaste _form, typeOfWaste waste)  {
	initComponents();
	form = _form;
	type = waste;
	lblName.setText(name);
	dKiloPerUnit = kilo;
	ImageIcon img = new ImageIcon(iconPath);
	lblIcon.setIcon(img);
	if (waste == typeOfWaste.RECYCLABLE){
	    setBackground(new Color(153,255,153));
	} else{
	    setBackground(new Color(255,152,152));
	}
	updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAmount = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        spnAmount = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(254, 188));
        setLayout(null);

        lblAmount.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        lblAmount.setText("Amount:");
        add(lblAmount);
        lblAmount.setBounds(20, 90, 101, 32);

        lblIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(lblIcon);
        lblIcon.setBounds(10, 10, 80, 70);

        lblName.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        lblName.setText("(NAME)");
        add(lblName);
        lblName.setBounds(100, 10, 290, 60);

        btnRemove.setText("REMOVE");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove);
        btnRemove.setBounds(140, 140, 100, 30);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(20, 140, 100, 30);

        spnAmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(spnAmount);
        spnAmount.setBounds(144, 100, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
	switch(type){
	    case RECYCLABLE:
		form.dRecyclable += dKiloPerUnit;
		System.out.println(form.dRecyclable);
		break;
	    case NON_RECYCLABLE:
		form.dNonRecyclable += dKiloPerUnit;
		System.out.println(form.dNonRecyclable);
		break;
	}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
	switch(type){
	    case RECYCLABLE:
		form.dRecyclable -= dKiloPerUnit;
		if(form.dRecyclable <0){
		    form.dRecyclable = 0;
		}
		System.out.println(form.dRecyclable);
		break;
	    case NON_RECYCLABLE:
		form.dNonRecyclable -= dKiloPerUnit;
		if(form.dNonRecyclable <0){
		    form.dNonRecyclable = 0;
		}
		System.out.println(form.dNonRecyclable);
		break;
	}
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblName;
    private javax.swing.JSpinner spnAmount;
    // End of variables declaration//GEN-END:variables
    public double dKiloPerUnit;
    public frmWaste form;
    public typeOfWaste type;
}
