package forms;

import java.awt.Color;
import javax.swing.ImageIcon;

public class pnlWasteBulk extends javax.swing.JPanel {
    /**
     * Creates new form pnlWaste
     */
    public pnlWasteBulk( frmWaste _form, pnlWaste.typeOfWaste waste)  {
	initComponents();
	form = _form;
	type = waste;
	if (waste == pnlWaste.typeOfWaste.RECYCLABLE){
	    setBackground(new Color(153,255,153));
	} else{
	    setBackground(new Color(255,152,152));
	}
	updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAmount = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblAmount1 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblAmount2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(254, 188));
        setLayout(null);

        lblAmount.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        lblAmount.setText("Kg");
        add(lblAmount);
        lblAmount.setBounds(230, 90, 40, 32);

        btnRemove.setText("REMOVE");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove);
        btnRemove.setBounds(150, 140, 100, 30);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(20, 140, 100, 30);

        lblAmount1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        lblAmount1.setText("Add or remove in bulk:");
        add(lblAmount1);
        lblAmount1.setBounds(10, 40, 270, 32);

        txtWeight.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        add(txtWeight);
        txtWeight.setBounds(120, 100, 100, 24);

        lblAmount2.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        lblAmount2.setText("Weight:");
        add(lblAmount2);
        lblAmount2.setBounds(10, 90, 101, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
	double weight = 0;
	try{
	    weight = Double.parseDouble(txtWeight.getText());
	} catch(NumberFormatException nfe){
	    System.out.println("Please enter valid input");
	    return;
	}
	switch(type){
	    case RECYCLABLE:
		form.dRecyclable += weight;
		form.dTotalRecyclable += weight;
		System.out.println(form.dRecyclable);
		break;
	    case NON_RECYCLABLE:
		form.dNonRecyclable += weight;
		form.dTotalNonRecyclable += weight;
		System.out.println(form.dNonRecyclable);
		break;
	}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
	double weight = 0;
	try{
	    weight = Double.parseDouble(txtWeight.getText());
	} catch(NumberFormatException nfe){
	    System.out.println("Please enter valid input");
	    return;
	}
	switch(type){
	    case RECYCLABLE:
		form.dRecyclable -= weight;
		if(form.dRecyclable <0){
		    form.dRecyclable = 0;
		} else {
		    form.dTotalRecyclable -= weight;
		}
		System.out.println(form.dRecyclable);
		break;
	    case NON_RECYCLABLE:
		form.dNonRecyclable -= weight;
		if(form.dNonRecyclable <0){
		    form.dNonRecyclable = 0;
		}else {
		    form.dTotalNonRecyclable -= weight;
		}
		System.out.println(form.dNonRecyclable);
		break;
	}
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
    public frmWaste form;
    public pnlWaste.typeOfWaste type;
}
